/**
 * sampleAnalytics.ts — SYNTHETIC data for the Interactive Analytics Showcase.
 *
 * Every number here is generated by a deterministic seeded PRNG and is
 * clearly labeled "sample data" in the UI. It represents nothing real.
 * The seeded generator keeps server and client renders identical
 * (no hydration mismatch).
 */

export interface SampleRow {
  month: string; // "Jan" … "Dec"
  monthIndex: number;
  category: "Retail" | "Corporate" | "Digital";
  revenue: number; // ₹ thousands
  users: number;
  conversion: number; // %
}

/** Mulberry32 — tiny deterministic PRNG. */
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
] as const;

const CATEGORIES = ["Retail", "Corporate", "Digital"] as const;

function buildSampleData(): SampleRow[] {
  const rand = mulberry32(20261009);
  const rows: SampleRow[] = [];
  CATEGORIES.forEach((category, c) => {
    const baseRevenue = [420, 780, 560][c];
    const baseUsers = [18_000, 9_500, 26_000][c];
    const baseConv = [3.2, 5.8, 4.4][c];
    MONTHS.forEach((month, m) => {
      const seasonal = 1 + 0.22 * Math.sin((m / 12) * Math.PI * 2 + c);
      const noise = 0.9 + rand() * 0.2;
      rows.push({
        month,
        monthIndex: m,
        category,
        revenue: Math.round(baseRevenue * seasonal * noise),
        users: Math.round(baseUsers * seasonal * noise),
        conversion: Math.round(baseConv * (0.92 + rand() * 0.16) * 10) / 10,
      });
    });
  });
  return rows;
}

export const sampleData: SampleRow[] = buildSampleData();

export const sampleDataCaption =
  "Sample data, for demonstration only — synthetic values generated for this UI, not real business data.";

export interface Kpi {
  label: string;
  value: number;
  format: "currency" | "number" | "percent";
}

export function formatKpi(kpi: Kpi): string {
  switch (kpi.format) {
    case "currency":
      return `₹${kpi.value.toLocaleString("en-IN")}k`;
    case "percent":
      return `${kpi.value.toFixed(1)}%`;
    default:
      return kpi.value.toLocaleString("en-IN");
  }
}

/** Aggregate KPIs for the given rows. */
export function computeKpis(rows: SampleRow[]): Kpi[] {
  const revenue = rows.reduce((s, r) => s + r.revenue, 0);
  const users = rows.reduce((s, r) => s + r.users, 0);
  const conversion =
    rows.length === 0
      ? 0
      : Math.round((rows.reduce((s, r) => s + r.conversion, 0) / rows.length) * 10) /
        10;
  const avgOrderValue = users === 0 ? 0 : Math.round((revenue * 1000) / users);
  return [
    { label: "Total Revenue", value: revenue, format: "currency" },
    { label: "Active Users", value: users, format: "number" },
    { label: "Avg. Conversion", value: conversion, format: "percent" },
    { label: "Avg. Order Value", value: avgOrderValue, format: "currency" },
  ];
}

/** Monthly totals across the selected categories (for the line chart). */
export function monthlyTotals(rows: SampleRow[]): { month: string; revenue: number }[] {
  return MONTHS.map((month, monthIndex) => ({
    month,
    revenue: rows
      .filter((r) => r.monthIndex === monthIndex)
      .reduce((s, r) => s + r.revenue, 0),
  }));
}

/** Per-category revenue totals (for the bar chart). */
export function categoryTotals(
  rows: SampleRow[],
): { category: string; revenue: number }[] {
  return CATEGORIES.map((category) => ({
    category,
    revenue: rows
      .filter((r) => r.category === category)
      .reduce((s, r) => s + r.revenue, 0),
  }));
}

export const sampleCategories = [...CATEGORIES];
export const dateRangePresets = [
  { label: "3M", months: 3 },
  { label: "6M", months: 6 },
  { label: "12M", months: 12 },
] as const;
